title: DHARPA
description: >- # this means to ignore newlines until "baseurl:"
  "Digital History Advanced Research Projects Accelerator"
baseurl: "/agency2" # the subpath of your site, e.g. /blog
url: ""
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
default_lang: en
languages:
  - en
  - de
